### ISSUE TITLE
Different Export Path .ts files in the .m3u8 Path

### ISSUE THREAD

**Issue by talaysa** [aminyazdanpanah/PHP-FFmpeg-video-streaming#13]
Hi,
Can you seperate export path and ts files in the .m3u8 path? When i put path to ->save(); , it is pushing same path to m3u8 file. Actually i need without folder path in m3u8 file, i'm keeping all files in the folder. It is causing mess in converter folder when i export without path. 

Example,
-> I'm exporting to export/movieName
-> Framework is pushing files names like export/movieName/file.ts

I need,
-> Export path will be again export/movieName
-> File names will be without export folder path

Just idea, i hope I've explained clear :)

**Comment by aminyazdanpanah** [comment]
If I understand you correctly, you wanted to split a directory of `ts` files into a subdirectory. It has been [added a method](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/commit/3648daa074c5cdcbefd3c6a3d04393efe1acddd0) named `setTsSubDirectory` in the HLS class. 

``` php
Streaming\FFMpeg::create()
    ->open('/path/to/file')
    ->HLS()
    ->setTsSubDirectory("ts_files")
    ->X264()
    ->autoGenerateRepresentations([240])
    ->save();
```

But there is a bug when the method is set. Unfortunately, when I set `strftime_mkdir` in the FFMpeg options, the whole expanded value of filename will be written into the m3u8 segment list(because I have to pass the full path of ts file to `hls_segment_filename ` option).

And you may see something like this in your manifest(m3u8):

``` text
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:11.200000,
/var/www/test/sub_ts/test2_144p_0000.ts
#EXTINF:9.600000,
/var/www/test/sub_ts/test2_144p_0001.ts
#EXTINF:9.600000,
/var/www/test/sub_ts/test2_144p_0002.ts
#EXTINF:9.600000,
/var/www/test/sub_ts/test2_144p_0003.ts
#EXTINF:11.200000,
/var/www/test/sub_ts/test2_144p_0004.ts
#EXTINF:8.833333,
/var/www/test/sub_ts/test2_144p_0005.ts
#EXT-X-ENDLIST
```
If you pass this manifest to player, you will occure an error!
I cannot fix it right now. Sorry!

If you can help with that, you can share your thoughts here. You can also fork the repository and fix the bug. After that, you just need to pull request to this repository.

**Comment by talaysa** [comment]
Hi,
It is not critical bug for now. Just cosmetic, but i will be researching how i can fix that bug when i have time. Thank you for advise!
