### ISSUE TITLE
can we run this in cron alert 

### ISSUE THREAD

**Issue by ngcgolf11** [aminyazdanpanah/PHP-FFmpeg-video-streaming#62]
can we run this one on cron alert and it will automatically do all the things. can it automatically detect input video resolution and transcode the video according to predefined streams can we use widewine or any drm tool with this one please help me in this matter.

**Comment by aminyazdanpanah** [comment]
You should create your own script to transcode your videos and run in it on a corn job. You can also use some libraries such as [Symphony(The Console Component)](https://github.com/symfony/console) and [Laravel(Queues)](https://github.com/illuminate/queue). 

You can use any DRM system such as Google's Widevine., Microsoft's PlayReady, and so on. You just need to fetch encryption keys from these DRM systems and encrypt your stream with the key you got. For example, you can use Guzzle to fetch the key and encrypt your stream using FFmpeg.

See [here](https://video.aminyazdanpanah.com/start?r=enc-hls#hls-encryption) for more information.

**Comment by aumkarthakur** [comment]
I have actually achieved it it's really easy all you have to do is create a php script which read all uploaded video and transcode it. I have a cronjob hitting that script every 10 min. So when any user upload any video after 10 min it gets transcoded and uploaded to AWS S3.

This was all possible because of this amazing library by @aminyazdanpanah .

Below are few screenshots:

![Screenshot 2020-06-21 at 7 22 03 PM](https://user-images.githubusercontent.com/20535658/85242816-e7c41180-b3f4-11ea-9bbb-b9e3f4301b24.png)
![Screenshot 2020-06-21 at 7 21 43 PM](https://user-images.githubusercontent.com/20535658/85242827-ec88c580-b3f4-11ea-8211-1e5600dffac1.png)
![Screenshot 2020-06-21 at 7 21 19 PM](https://user-images.githubusercontent.com/20535658/85242830-ed215c00-b3f4-11ea-9077-0bd7ab73b2ec.png)

**Comment by ngcgolf11** [comment]
@aumkarthakur  Can you share me your php script please I am requesting you bro

**Comment by aumkarthakur** [comment]
@ngcgolf11  Sorry bro but it's Intellectual property of IPSTUDIO (the company I work for). I have no right over it.

**Comment by ngcgolf11** [comment]
can you guide me how i can write code or any sample on the base of my own code
